<a href="https://colab.research.google.com/github/ShenlyR/Volume-Lambung-Perahu/blob/main/Hitung_Volume_Lambung_Perahu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nama:** Shenly Lestari Riada

**NPM:** 25083010019

**Kelas:** A

**Link Github:** https://github.com/ShenlyR/Volume-Lambung-Perahu.git

**Import Library**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from scipy.integrate import simpson, trapezoid

**Grid Tampak Atas**

In [2]:
ukuran_dash = 5
ukuran_celah = 5

# satu kotak interval
jumlah_dash_0 = 4
jumlah_celah_0 = 5

lebar_0_cm = (jumlah_dash_0 * ukuran_dash) + (jumlah_celah_0 * ukuran_celah)
lebar_0_m = lebar_0_cm / 100

print("Lebar titik 0:", lebar_0_cm, "cm")
print("Lebar titik 0:", lebar_0_m, "m")

Lebar titik 0: 45 cm
Lebar titik 0: 0.45 m

**Interval Tampak Atas**

In [3]:
jumlah_interval_atas = 16
panjang_kapal = 4.0

interval_m_atas = panjang_kapal / jumlah_interval_atas

print("Interval tampak atas =", interval_m_atas, "m")

Interval tampak atas = 0.25 m

In [4]:
# Jumlah interval tampak atas
jumlah_interval_atas = 16

# Jarak antar titik
interval_m_atas = 4.0 / jumlah_interval_atas

# Membuat titik
titik_atas = np.arange(jumlah_interval_atas + 1)

# Menghitung jarak setiap titik
jarak_atas = titik_atas * interval_m_atas

hasil_tampak_atas = pd.DataFrame({
    "Titik": titik_atas,
    "Jarak(m)": jarak_atas
})

hasil_tampak_atas["Jarak(m)"] = (
    hasil_tampak_atas["Jarak(m)"].round(2)
)

hasil_tampak_atas

    Titik  Jarak(m)
0       0      0.00
1       1      0.25
2       2      0.50
3       3      0.75
4       4      1.00
5       5      1.25
6       6      1.50
7       7      1.75
8       8      2.00
9       9      2.25
10     10      2.50
11     11      2.75
12     12      3.00
13     13      3.25
14     14      3.50
15     15      3.75
16     16      4.00

**Grid Tampak Samping**

In [5]:
ukuran_dash = 5
ukuran_celah = 5

panjang_kapal = 4.0
jumlah_interval_samping = 20

interval_samping_m = panjang_kapal / jumlah_interval_samping

print("Jumlah interval:", jumlah_interval_samping)
print("Jarak 1 interval:", interval_samping_m, "m")

Jumlah interval: 20
Jarak 1 interval: 0.2 m

**Interval Tampak Samping**

In [6]:
panjang_samping = jumlah_interval_samping * interval_samping_m

print("Jumlah interval:", jumlah_interval_samping)
print("Panjang tampak samping:", panjang_samping, "m")

Jumlah interval: 20
Panjang tampak samping: 4.0 m

In [7]:
titik_samping = np.arange(jumlah_interval_samping + 1)
jarak_samping = titik_samping * interval_samping_m

hasil_tampak_samping = pd.DataFrame({
    "Titik": titik_samping,
    "Jarak(m)": jarak_samping
})

hasil_tampak_samping["Jarak(m)"] = hasil_tampak_samping["Jarak(m)"].round(2)
hasil_tampak_samping

    Titik  Jarak(m)
0       0       0.0
1       1       0.2
2       2       0.4
3       3       0.6
4       4       0.8
5       5       1.0
6       6       1.2
7       7       1.4
8       8       1.6
9       9       1.8
10     10       2.0
11     11       2.2
12     12       2.4
13     13       2.6
14     14       2.8
15     15       3.0
16     16       3.2
17     17       3.4
18     18       3.6
19     19       3.8
20     20       4.0

In [8]:
tinggi_samping = np.array([
    0.15, 0.27, 0.36, 0.42, 0.47,
    0.50, 0.51, 0.52, 0.52, 0.52,
    0.52, 0.52, 0.52, 0.52, 0.51,
    0.48, 0.43, 0.38, 0.33, 0.24,
    0.01
])

hasil_tampak_samping["Tinggi (m)"] = tinggi_samping
hasil_tampak_samping

    Titik  Jarak(m)  Tinggi (m)
0       0       0.0        0.15
1       1       0.2        0.27
2       2       0.4        0.36
3       3       0.6        0.42
4       4       0.8        0.47
5       5       1.0        0.50
6       6       1.2        0.51
7       7       1.4        0.52
8       8       1.6        0.52
9       9       1.8        0.52
10     10       2.0        0.52
11     11       2.2        0.52
12     12       2.4        0.52
13     13       2.6        0.52
14     14       2.8        0.51
15     15       3.0        0.48
16     16       3.2        0.43
17     17       3.4        0.38
18     18       3.6        0.33
19     19       3.8        0.24
20     20       4.0        0.01

**Gabungan Tampak Atas dan Tampak Samping**

In [9]:
# Jumlah interval tampak atas
jumlah_interval_atas = 20

titik_atas = np.arange(jumlah_interval_atas + 1)

# Jarak antar titik = 4 / 20 = 0.2 m
interval_m_atas = 4.0 / jumlah_interval_atas

# Posisi setiap titik
jarak_atas = titik_atas * interval_m_atas

# Lebar lambung tampak atas
lebar_atas = np.array([
    0.45, 0.60, 0.70, 0.75, 0.80,
    0.80, 0.80, 0.80, 0.80, 0.80,
    0.80, 0.80, 0.80, 0.80, 0.80,
    0.75, 0.70, 0.60, 0.50, 0.35,
    0.15
])

# Posisi tampak samping
x_samping = jarak_samping

# ke posisi titik tampak atas
tinggi_atas = np.interp(
    jarak_atas,
    x_samping,
    tinggi_samping
)

hasil_tinggi_atas = pd.DataFrame({
    "Titik": titik_atas,
    "Jarak (m)": jarak_atas,
    "Lebar (m)": lebar_atas,
    "Tinggi (m)": tinggi_atas
})

# Membulatkan untuk tampilan
hasil_tinggi_atas["Jarak (m)"] = hasil_tinggi_atas["Jarak (m)"].round(2)
hasil_tinggi_atas["Lebar (m)"] = hasil_tinggi_atas["Lebar (m)"].round(2)
hasil_tinggi_atas["Tinggi (m)"] = hasil_tinggi_atas["Tinggi (m)"].round(3)

hasil_tinggi_atas

    Titik  Jarak (m)  Lebar (m)  Tinggi (m)
0       0        0.0       0.45        0.15
1       1        0.2       0.60        0.27
2       2        0.4       0.70        0.36
3       3        0.6       0.75        0.42
4       4        0.8       0.80        0.47
5       5        1.0       0.80        0.50
6       6        1.2       0.80        0.51
7       7        1.4       0.80        0.52
8       8        1.6       0.80        0.52
9       9        1.8       0.80        0.52
10     10        2.0       0.80        0.52
11     11        2.2       0.80        0.52
12     12        2.4       0.80        0.52
13     13        2.6       0.80        0.52
14     14        2.8       0.80        0.51
15     15        3.0       0.75        0.48
16     16        3.2       0.70        0.43
17     17        3.4       0.60        0.38
18     18        3.6       0.50        0.33
19     19        3.8       0.35        0.24
20     20        4.0       0.15        0.01

In [10]:
# hitung luas penampang
hasil_tinggi_atas["Luas Penampang (m2)"] = (
    hasil_tinggi_atas["Lebar (m)"] *
    hasil_tinggi_atas["Tinggi (m)"]
)

hasil_tinggi_atas["Luas Penampang (m2)"] = (
    hasil_tinggi_atas["Luas Penampang (m2)"].round(4)
)

hasil_tinggi_atas

    Titik  Jarak (m)  Lebar (m)  Tinggi (m)  Luas Penampang (m2)
0       0        0.0       0.45        0.15               0.0675
1       1        0.2       0.60        0.27               0.1620
2       2        0.4       0.70        0.36               0.2520
3       3        0.6       0.75        0.42               0.3150
4       4        0.8       0.80        0.47               0.3760
5       5        1.0       0.80        0.50               0.4000
6       6        1.2       0.80        0.51               0.4080
7       7        1.4       0.80        0.52               0.4160
8       8        1.6       0.80        0.52               0.4160
9       9        1.8       0.80        0.52               0.4160
10     10        2.0       0.80        0.52               0.4160
11     11        2.2       0.80        0.52               0.4160
12     12        2.4       0.80        0.52               0.4160
13     13        2.6       0.80        0.52               0.4160
14     14        2.8       0.80        0.51               0.4080
15     15        3.0       0.75        0.48               0.3600
16     16        3.2       0.70        0.43               0.3010
17     17        3.4       0.60        0.38               0.2280
18     18        3.6       0.50        0.33               0.1650
19     19        3.8       0.35        0.24               0.0840
20     20        4.0       0.15        0.01               0.0015

**Hitung Volume Lambung Kapal**

**Aturan Simpson 1/3**

Rumus:

In [11]:
# data luas penampang
luas = hasil_tinggi_atas["Luas Penampang (m2)"].values

# aturan Simpson 1/3
volume_satu_lambung = (
    interval_m_atas / 3 *
    (
        luas[0]
        + luas[-1]
        + 4 * luas[1:-1:2].sum()
        + 2 * luas[2:-1:2].sum()
    )
)

volume_satu_lambung = round(volume_satu_lambung, 4)
print("Volume satu lambung =", volume_satu_lambung, "m3")

Volume satu lambung = 1.2825 m3

In [12]:
# Volume kedua lambung
volume_kedua_lambung = 2 * volume_satu_lambung

print(
    "Volume kedua lambung =",
    volume_kedua_lambung,
    "m3"
)

Volume kedua lambung = 2.565 m3

**Aturan Trapesium**

In [13]:
# aturan trapesium
volume_trapesium = (
    interval_m_atas *
    (
        (luas[0] + luas[-1]) / 2
        + luas[1:-1].sum()
    )
)

print("Volume satu lambung - Trapesium =",
      volume_trapesium, "m3")

Volume satu lambung - Trapesium = 1.2811000000000001 m3

In [14]:
# volume kedua lambung
volume_kedua_trapesium = 2 * volume_trapesium

print(
    "Volume kedua lambung - Trapesium =",
    volume_kedua_trapesium,
    "m3"
)

Volume kedua lambung - Trapesium = 2.5622000000000003 m3

**Hasil Perbandingan Antara kedua Aturan**

In [15]:
hasil_akhir = pd.DataFrame({
    "Aturan": [
        "Simpson 1/3",
        "Trapesium"
    ],
    "Volume 1 Lambung (m3)": [
        volume_satu_lambung,
        volume_trapesium
    ],
    "Volume 2 Lambung (m3)": [
        volume_kedua_lambung,
        volume_kedua_trapesium
    ]
})

hasil_akhir["Volume 1 Lambung (m3)"] = hasil_akhir["Volume 1 Lambung (m3)"].round(5)
hasil_akhir["Volume 2 Lambung (m3)"] = hasil_akhir["Volume 2 Lambung (m3)"].round(5)

hasil_akhir

        Aturan  Volume 1 Lambung (m3)  Volume 2 Lambung (m3)
0  Simpson 1/3                 1.2825                 2.5650
1    Trapesium                 1.2811                 2.5622

**Kesimpulan**

Berdasarkan hasil perhitungan, volume dari satu lambung perahu dengan metode Simpson 1/3 sebesar 1,60310 m³, sedangkan metode trapesium memberikan hasil sebesar 1,60138 m³.
Volume kedua lambung, masing-masing bernilai 3,20620 m³ dan 3,20275 m³.
Hasil kedua metode cukup dekat, sehingga perbedaannya relatif kecil